// Decompiled with JetBrains decompiler
// Type: Thống_kê_xổ_số.TabLoaiLoto
// Assembly: SINHTAISINHLOC, Version=6.0.0.6, Culture=neutral, PublicKeyToken=null
// MVID: 14ECBB60-AC76-4B86-9AB8-7862FB51126A
// Assembly location: C:\Program Files (x86)\SINH TAI SINH LOC\SINHTAISINHLOC.exe

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace Thống_kê_xổ_số
{
  public class TabLoaiLoto : UserControl
  {
    private IContainer components = (IContainer) null;
    private Panel panel1;
    private Label label2;
    private RadioButton rdTuDo;
    private RadioButton rdTrungDuoi;
    private RadioButton rdTrungDau;
    private RadioButton rdBachThu;
    private RadioButton rdCap;
    private Label label1;
    private TextBox txtBiendongay;
    private Button btnThongke;
    private DateTimePicker dtNgayXem;
    private Label label3;
    private DataGridView dtg_Ketqua;
    private DataGridViewTextBoxColumn stt;
    private DataGridViewTextBoxColumn loto;
    private DataGridViewTextBoxColumn solanve;
    private DataGridViewTextBoxColumn chuKi;
    private DataGridViewTextBoxColumn ngayChuara;
    private DataGridViewTextBoxColumn maxSobanghi;
    private DataGridViewTextBoxColumn maxGan;
    private DataGridViewTextBoxColumn diemtanxuat;
    private DataGridViewTextBoxColumn diemGan;
    private DataGridViewTextBoxColumn tuongQuan;
    private DataGridViewTextBoxColumn veNgay;
    private DataGridViewTextBoxColumn colTrong;

    public TabLoaiLoto()
    {
      this.InitializeComponent();
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      DataGridViewCellStyle gridViewCellStyle1 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle2 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle3 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle4 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle5 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle6 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle7 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle8 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle9 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle10 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle11 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle12 = new DataGridViewCellStyle();
      DataGridViewCellStyle gridViewCellStyle13 = new DataGridViewCellStyle();
      this.panel1 = new Panel();
      this.label2 = new Label();
      this.rdTuDo = new RadioButton();
      this.rdTrungDuoi = new RadioButton();
      this.rdTrungDau = new RadioButton();
      this.rdBachThu = new RadioButton();
      this.rdCap = new RadioButton();
      this.label1 = new Label();
      this.txtBiendongay = new TextBox();
      this.btnThongke = new Button();
      this.dtNgayXem = new DateTimePicker();
      this.label3 = new Label();
      this.dtg_Ketqua = new DataGridView();
      this.stt = new DataGridViewTextBoxColumn();
      this.loto = new DataGridViewTextBoxColumn();
      this.solanve = new DataGridViewTextBoxColumn();
      this.chuKi = new DataGridViewTextBoxColumn();
      this.ngayChuara = new DataGridViewTextBoxColumn();
      this.maxSobanghi = new DataGridViewTextBoxColumn();
      this.maxGan = new DataGridViewTextBoxColumn();
      this.diemtanxuat = new DataGridViewTextBoxColumn();
      this.diemGan = new DataGridViewTextBoxColumn();
      this.tuongQuan = new DataGridViewTextBoxColumn();
      this.veNgay = new DataGridViewTextBoxColumn();
      this.colTrong = new DataGridViewTextBoxColumn();
      this.panel1.SuspendLayout();
      ((ISupportInitialize) this.dtg_Ketqua).BeginInit();
      this.SuspendLayout();
      this.panel1.Controls.Add((Control) this.label2);
      this.panel1.Controls.Add((Control) this.rdTuDo);
      this.panel1.Controls.Add((Control) this.rdTrungDuoi);
      this.panel1.Controls.Add((Control) this.rdTrungDau);
      this.panel1.Controls.Add((Control) this.rdBachThu);
      this.panel1.Controls.Add((Control) this.rdCap);
      this.panel1.Controls.Add((Control) this.label1);
      this.panel1.Controls.Add((Control) this.txtBiendongay);
      this.panel1.Controls.Add((Control) this.btnThongke);
      this.panel1.Controls.Add((Control) this.dtNgayXem);
      this.panel1.Controls.Add((Control) this.label3);
      this.panel1.Dock = DockStyle.Top;
      this.panel1.Location = new Point(0, 0);
      this.panel1.Name = "panel1";
      this.panel1.Size = new Size(1217, 80);
      this.panel1.TabIndex = 1;
      this.label2.AutoSize = true;
      this.label2.BackColor = Color.Transparent;
      this.label2.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label2.ForeColor = Color.Black;
      this.label2.Location = new Point(7, 10);
      this.label2.Name = "label2";
      this.label2.Size = new Size(65, 16);
      this.label2.TabIndex = 39;
      this.label2.Text = "Xem ngày";
      this.rdTuDo.AutoSize = true;
      this.rdTuDo.Cursor = Cursors.Hand;
      this.rdTuDo.FlatStyle = FlatStyle.Flat;
      this.rdTuDo.ForeColor = Color.Black;
      this.rdTuDo.Location = new Point(797, 10);
      this.rdTuDo.Name = "rdTuDo";
      this.rdTuDo.Size = new Size(101, 19);
      this.rdTuDo.TabIndex = 6;
      this.rdTuDo.Text = "Lô Cặp Tự Do";
      this.rdTuDo.UseVisualStyleBackColor = true;
      this.rdTrungDuoi.AutoSize = true;
      this.rdTrungDuoi.Cursor = Cursors.Hand;
      this.rdTrungDuoi.FlatStyle = FlatStyle.Flat;
      this.rdTrungDuoi.ForeColor = Color.Black;
      this.rdTrungDuoi.Location = new Point(703, 10);
      this.rdTrungDuoi.Name = "rdTrungDuoi";
      this.rdTrungDuoi.Size = new Size(85, 19);
      this.rdTrungDuoi.TabIndex = 5;
      this.rdTrungDuoi.Text = "Trùng Đuôi";
      this.rdTrungDuoi.UseVisualStyleBackColor = true;
      this.rdTrungDau.AutoSize = true;
      this.rdTrungDau.Cursor = Cursors.Hand;
      this.rdTrungDau.FlatStyle = FlatStyle.Flat;
      this.rdTrungDau.ForeColor = Color.Black;
      this.rdTrungDau.Location = new Point(612, 10);
      this.rdTrungDau.Name = "rdTrungDau";
      this.rdTrungDau.Size = new Size(82, 19);
      this.rdTrungDau.TabIndex = 4;
      this.rdTrungDau.Text = "Trùng Đầu";
      this.rdTrungDau.UseVisualStyleBackColor = true;
      this.rdBachThu.AutoSize = true;
      this.rdBachThu.Cursor = Cursors.Hand;
      this.rdBachThu.FlatStyle = FlatStyle.Flat;
      this.rdBachThu.ForeColor = Color.Black;
      this.rdBachThu.Location = new Point(527, 10);
      this.rdBachThu.Name = "rdBachThu";
      this.rdBachThu.Size = new Size(76, 19);
      this.rdBachThu.TabIndex = 3;
      this.rdBachThu.Text = "Bạch Thủ";
      this.rdBachThu.UseVisualStyleBackColor = true;
      this.rdCap.AutoSize = true;
      this.rdCap.Checked = true;
      this.rdCap.Cursor = Cursors.Hand;
      this.rdCap.FlatStyle = FlatStyle.Flat;
      this.rdCap.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.rdCap.ForeColor = Color.Red;
      this.rdCap.Location = new Point(452, 10);
      this.rdCap.Name = "rdCap";
      this.rdCap.Size = new Size(63, 19);
      this.rdCap.TabIndex = 2;
      this.rdCap.TabStop = true;
      this.rdCap.Text = "Lô Cặp";
      this.rdCap.UseVisualStyleBackColor = true;
      this.label1.AutoSize = true;
      this.label1.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label1.ForeColor = Color.Black;
      this.label1.Location = new Point(323, 10);
      this.label1.Name = "label1";
      this.label1.Size = new Size(89, 16);
      this.label1.TabIndex = 38;
      this.label1.Text = "ngày về trước";
      this.txtBiendongay.BorderStyle = BorderStyle.FixedSingle;
      this.txtBiendongay.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.txtBiendongay.ForeColor = Color.Red;
      this.txtBiendongay.Location = new Point(269, 8);
      this.txtBiendongay.Name = "txtBiendongay";
      this.txtBiendongay.Size = new Size(51, 21);
      this.txtBiendongay.TabIndex = 1;
      this.txtBiendongay.Text = "36";
      this.btnThongke.BackColor = Color.Teal;
      this.btnThongke.Cursor = Cursors.Hand;
      this.btnThongke.FlatStyle = FlatStyle.Flat;
      this.btnThongke.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.btnThongke.ForeColor = Color.White;
      this.btnThongke.Location = new Point(946, 7);
      this.btnThongke.Margin = new Padding(3, 0, 3, 0);
      this.btnThongke.Name = "btnThongke";
      this.btnThongke.Size = new Size(100, 24);
      this.btnThongke.TabIndex = 7;
      this.btnThongke.Text = "Thống Kê";
      this.btnThongke.TextAlign = ContentAlignment.TopCenter;
      this.btnThongke.UseVisualStyleBackColor = true;
      this.dtNgayXem.CalendarFont = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dtNgayXem.CalendarForeColor = Color.Red;
      this.dtNgayXem.CalendarMonthBackground = SystemColors.Info;
      this.dtNgayXem.CustomFormat = "dd/MM/yyyy";
      this.dtNgayXem.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.dtNgayXem.Format = DateTimePickerFormat.Custom;
      this.dtNgayXem.Location = new Point(72, 8);
      this.dtNgayXem.MinDate = new DateTime(2005, 1, 5, 0, 0, 0, 0);
      this.dtNgayXem.Name = "dtNgayXem";
      this.dtNgayXem.Size = new Size(91, 21);
      this.dtNgayXem.TabIndex = 0;
      this.label3.AutoSize = true;
      this.label3.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label3.ForeColor = Color.Black;
      this.label3.Location = new Point(217, 11);
      this.label3.Name = "label3";
      this.label3.Size = new Size(50, 16);
      this.label3.TabIndex = 36;
      this.label3.Text = "biên độ";
      this.dtg_Ketqua.AllowUserToAddRows = false;
      this.dtg_Ketqua.AllowUserToDeleteRows = false;
      this.dtg_Ketqua.AllowUserToResizeRows = false;
      this.dtg_Ketqua.BackgroundColor = SystemColors.ButtonHighlight;
      this.dtg_Ketqua.BorderStyle = BorderStyle.None;
      this.dtg_Ketqua.CellBorderStyle = DataGridViewCellBorderStyle.RaisedHorizontal;
      gridViewCellStyle1.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle1.BackColor = Color.Teal;
      gridViewCellStyle1.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle1.ForeColor = Color.White;
      gridViewCellStyle1.SelectionBackColor = SystemColors.Highlight;
      gridViewCellStyle1.SelectionForeColor = SystemColors.HighlightText;
      gridViewCellStyle1.WrapMode = DataGridViewTriState.True;
      this.dtg_Ketqua.ColumnHeadersDefaultCellStyle = gridViewCellStyle1;
      this.dtg_Ketqua.ColumnHeadersHeight = 24;
      this.dtg_Ketqua.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
      this.dtg_Ketqua.Columns.AddRange((DataGridViewColumn) this.stt, (DataGridViewColumn) this.loto, (DataGridViewColumn) this.solanve, (DataGridViewColumn) this.chuKi, (DataGridViewColumn) this.ngayChuara, (DataGridViewColumn) this.maxSobanghi, (DataGridViewColumn) this.maxGan, (DataGridViewColumn) this.diemtanxuat, (DataGridViewColumn) this.diemGan, (DataGridViewColumn) this.tuongQuan, (DataGridViewColumn) this.veNgay, (DataGridViewColumn) this.colTrong);
      gridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle2.BackColor = SystemColors.Window;
      gridViewCellStyle2.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle2.ForeColor = SystemColors.ControlText;
      gridViewCellStyle2.SelectionBackColor = Color.Azure;
      gridViewCellStyle2.SelectionForeColor = Color.Black;
      gridViewCellStyle2.WrapMode = DataGridViewTriState.False;
      this.dtg_Ketqua.DefaultCellStyle = gridViewCellStyle2;
      this.dtg_Ketqua.Dock = DockStyle.Fill;
      this.dtg_Ketqua.GridColor = Color.WhiteSmoke;
      this.dtg_Ketqua.Location = new Point(0, 80);
      this.dtg_Ketqua.Margin = new Padding(0);
      this.dtg_Ketqua.MultiSelect = false;
      this.dtg_Ketqua.Name = "dtg_Ketqua";
      this.dtg_Ketqua.ReadOnly = true;
      this.dtg_Ketqua.RowHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
      gridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle3.BackColor = Color.Cornsilk;
      gridViewCellStyle3.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle3.ForeColor = SystemColors.WindowText;
      gridViewCellStyle3.SelectionBackColor = SystemColors.Highlight;
      gridViewCellStyle3.SelectionForeColor = SystemColors.HighlightText;
      gridViewCellStyle3.WrapMode = DataGridViewTriState.True;
      this.dtg_Ketqua.RowHeadersDefaultCellStyle = gridViewCellStyle3;
      this.dtg_Ketqua.RowHeadersVisible = false;
      this.dtg_Ketqua.RowTemplate.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
      this.dtg_Ketqua.RowTemplate.Height = 24;
      this.dtg_Ketqua.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
      this.dtg_Ketqua.Size = new Size(1217, 467);
      this.dtg_Ketqua.TabIndex = 4;
      this.stt.AutoSizeMode = DataGridViewAutoSizeColumnMode.None;
      this.stt.DataPropertyName = "stt";
      gridViewCellStyle4.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle4.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 163);
      gridViewCellStyle4.ForeColor = Color.Gray;
      this.stt.DefaultCellStyle = gridViewCellStyle4;
      this.stt.HeaderText = "STT ";
      this.stt.Name = "stt";
      this.stt.ReadOnly = true;
      this.stt.Width = 45;
      this.loto.DataPropertyName = "loto";
      gridViewCellStyle5.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle5.BackColor = SystemColors.ButtonHighlight;
      gridViewCellStyle5.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle5.ForeColor = Color.Red;
      this.loto.DefaultCellStyle = gridViewCellStyle5;
      this.loto.HeaderText = "Bộ số";
      this.loto.Name = "loto";
      this.loto.ReadOnly = true;
      this.loto.ToolTipText = "Lô tạo thành";
      this.loto.Width = 90;
      this.solanve.DataPropertyName = "solanve";
      gridViewCellStyle6.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 163);
      this.solanve.DefaultCellStyle = gridViewCellStyle6;
      this.solanve.HeaderText = "Số lần về";
      this.solanve.Name = "solanve";
      this.solanve.ReadOnly = true;
      this.solanve.ToolTipText = "Số lần về của lô tô trong khung kiểm tra";
      this.chuKi.DataPropertyName = "chuKi";
      gridViewCellStyle7.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 163);
      this.chuKi.DefaultCellStyle = gridViewCellStyle7;
      this.chuKi.HeaderText = "Chu kỳ (ngày)";
      this.chuKi.Name = "chuKi";
      this.chuKi.ReadOnly = true;
      this.chuKi.ToolTipText = "Chu kỳ trung bình để lô tô về lại";
      this.ngayChuara.DataPropertyName = "ngayChuara";
      gridViewCellStyle8.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      gridViewCellStyle8.ForeColor = Color.Red;
      this.ngayChuara.DefaultCellStyle = gridViewCellStyle8;
      this.ngayChuara.HeaderText = "Ngày chưa ra";
      this.ngayChuara.Name = "ngayChuara";
      this.ngayChuara.ReadOnly = true;
      this.ngayChuara.ToolTipText = "Số ngày chưa ra của lô tô";
      this.ngayChuara.Width = 120;
      this.maxSobanghi.DataPropertyName = "maxSobanghi";
      gridViewCellStyle9.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 163);
      this.maxSobanghi.DefaultCellStyle = gridViewCellStyle9;
      this.maxSobanghi.HeaderText = "Max trong khung";
      this.maxSobanghi.Name = "maxSobanghi";
      this.maxSobanghi.ReadOnly = true;
      this.maxSobanghi.ToolTipText = "Khoảng ngày chưa ra lớn nhất trong khung kiểm tra";
      this.maxSobanghi.Width = 110;
      this.maxGan.DataPropertyName = "maxGan";
      gridViewCellStyle10.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle10.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 163);
      this.maxGan.DefaultCellStyle = gridViewCellStyle10;
      this.maxGan.HeaderText = "Max (+2năm)";
      this.maxGan.Name = "maxGan";
      this.maxGan.ReadOnly = true;
      this.maxGan.ToolTipText = "Khoảng ngày chưa ra lớn nhất trong khung kiểm tra + 2 năm";
      this.diemtanxuat.DataPropertyName = "diemtanxuat";
      gridViewCellStyle11.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle11.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle11.ForeColor = Color.Red;
      this.diemtanxuat.DefaultCellStyle = gridViewCellStyle11;
      this.diemtanxuat.HeaderText = "Điểm tần xuất";
      this.diemtanxuat.Name = "diemtanxuat";
      this.diemtanxuat.ReadOnly = true;
      this.diemtanxuat.ToolTipText = "Điểm tần xuất đạt được trong MAX I";
      this.diemtanxuat.Width = 130;
      this.diemGan.DataPropertyName = "diemGan";
      gridViewCellStyle12.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle12.Font = new Font("Arial Narrow", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle12.ForeColor = Color.Red;
      this.diemGan.DefaultCellStyle = gridViewCellStyle12;
      this.diemGan.HeaderText = "Điểm gan";
      this.diemGan.Name = "diemGan";
      this.diemGan.ReadOnly = true;
      this.diemGan.ToolTipText = "Điểm gan đạt được trong MAX II";
      this.diemGan.Width = 130;
      this.tuongQuan.DataPropertyName = "tuongQuan";
      this.tuongQuan.HeaderText = "Tổng Điểm";
      this.tuongQuan.Name = "tuongQuan";
      this.tuongQuan.ReadOnly = true;
      this.veNgay.DataPropertyName = "veNgay";
      gridViewCellStyle13.Alignment = DataGridViewContentAlignment.MiddleCenter;
      gridViewCellStyle13.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      gridViewCellStyle13.ForeColor = Color.Blue;
      this.veNgay.DefaultCellStyle = gridViewCellStyle13;
      this.veNgay.HeaderText = "Về ngày";
      this.veNgay.Name = "veNgay";
      this.veNgay.ReadOnly = true;
      this.veNgay.ToolTipText = "Ngày về của lô tô";
      this.colTrong.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
      this.colTrong.DataPropertyName = "colTrong";
      this.colTrong.HeaderText = "";
      this.colTrong.Name = "colTrong";
      this.colTrong.ReadOnly = true;
      this.AutoScaleDimensions = new SizeF(7f, 15f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.BackColor = Color.White;
      this.Controls.Add((Control) this.dtg_Ketqua);
      this.Controls.Add((Control) this.panel1);
      this.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Name = nameof (TabLoaiLoto);
      this.Size = new Size(1217, 547);
      this.panel1.ResumeLayout(false);
      this.panel1.PerformLayout();
      ((ISupportInitialize) this.dtg_Ketqua).EndInit();
      this.ResumeLayout(false);
    }
  }
}
