//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessCoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfigBacNho
    {
        public int Stt { get; set; }
        public string UserId { get; set; }
        public Nullable<int> KhungDanhLoCapNuoi { get; set; }
        public Nullable<int> KhungDanhBachThuNuoi { get; set; }
        public Nullable<int> KhungDanhDacBietNuoi { get; set; }
        public Nullable<int> KhungLoXien2 { get; set; }
        public Nullable<int> HienThiNgayVe { get; set; }
        public Nullable<int> BiendoTrungDau { get; set; }
        public Nullable<int> BiendoTrungDuoi { get; set; }
        public Nullable<int> SoBanGhi { get; set; }
        public Nullable<int> TheoGiai { get; set; }
        public Nullable<int> TheoNhay { get; set; }
        public Nullable<int> TheoCap { get; set; }
        public Nullable<int> DauCam { get; set; }
        public Nullable<int> DuoiCam { get; set; }
        public Nullable<int> CapCungVe { get; set; }
        public Nullable<int> DanCungVe { get; set; }
        public Nullable<int> BacNhoTheoThu { get; set; }
        public Nullable<int> ThongKeCauDep { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
    }
}
