//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessCoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKetqua
    {
        public System.DateTime NgayMoThuong { get; set; }
        public string G0 { get; set; }
        public string G1 { get; set; }
        public string G21 { get; set; }
        public string G22 { get; set; }
        public string G31 { get; set; }
        public string G32 { get; set; }
        public string G33 { get; set; }
        public string G34 { get; set; }
        public string G35 { get; set; }
        public string G36 { get; set; }
        public string G41 { get; set; }
        public string G42 { get; set; }
        public string G43 { get; set; }
        public string G44 { get; set; }
        public string G51 { get; set; }
        public string G52 { get; set; }
        public string G53 { get; set; }
        public string G54 { get; set; }
        public string G55 { get; set; }
        public string G56 { get; set; }
        public string G61 { get; set; }
        public string G62 { get; set; }
        public string G63 { get; set; }
        public string G71 { get; set; }
        public string G72 { get; set; }
        public string G73 { get; set; }
        public string G74 { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
