//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessCoreLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public string UserId { get; set; }
        public string Email { get; set; }
        public string Pwd { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
