USE [master]
GO

/****** Object:  Database [Lotodb]    Script Date: 9/5/2018 9:06:32 AM ******/
CREATE DATABASE [Lotodb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lotodb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MEPCSERVER\MSSQL\DATA\Lotodb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lotodb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MEPCSERVER\MSSQL\DATA\Lotodb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Lotodb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lotodb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lotodb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lotodb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lotodb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lotodb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lotodb] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lotodb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lotodb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lotodb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lotodb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lotodb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lotodb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lotodb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lotodb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lotodb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lotodb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lotodb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lotodb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lotodb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lotodb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lotodb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lotodb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lotodb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lotodb] SET RECOVERY FULL 
GO

ALTER DATABASE [Lotodb] SET  MULTI_USER 
GO

ALTER DATABASE [Lotodb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lotodb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lotodb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lotodb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Lotodb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lotodb] SET QUERY_STORE = OFF
GO

USE [Lotodb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Lotodb] SET  READ_WRITE 
GO


