// Decompiled with JetBrains decompiler
// Type: Thống_kê_xổ_số.FormUI.TabTanxuatcaploto
// Assembly: SINHTAISINHLOC, Version=6.0.0.6, Culture=neutral, PublicKeyToken=null
// MVID: 14ECBB60-AC76-4B86-9AB8-7862FB51126A
// Assembly location: C:\Program Files (x86)\SINH TAI SINH LOC\SINHTAISINHLOC.exe

using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace Thống_kê_xổ_số.FormUI
{
  public class TabTanxuatcaploto : UserControl
  {
    private IContainer components = (IContainer) null;
    private Panel panel2;
    private Label label6;
    private Label label5;
    private Button btnTronhet;
    private CheckBox cb80;
    private CheckBox cb60;
    private CheckBox cb40;
    private CheckBox cb20;
    private CheckBox cb00;
    private CheckBox cb89;
    private CheckBox cb88;
    private CheckBox cb87;
    private CheckBox cb86;
    private CheckBox cb85;
    private CheckBox cb84;
    private CheckBox cb83;
    private CheckBox cb82;
    private CheckBox cb81;
    private CheckBox cb69;
    private CheckBox cb68;
    private CheckBox cb67;
    private CheckBox cb66;
    private CheckBox cb65;
    private CheckBox cb64;
    private CheckBox cb63;
    private CheckBox cb62;
    private CheckBox cb61;
    private CheckBox cb49;
    private CheckBox cb48;
    private CheckBox cb47;
    private CheckBox cb46;
    private CheckBox cb45;
    private CheckBox cb44;
    private CheckBox cb43;
    private CheckBox cb42;
    private CheckBox cb41;
    private CheckBox cb29;
    private CheckBox cb28;
    private CheckBox cb27;
    private CheckBox cb26;
    private CheckBox cb25;
    private CheckBox cb24;
    private CheckBox cb23;
    private CheckBox cb22;
    private CheckBox cb21;
    private CheckBox cb09;
    private CheckBox cb08;
    private CheckBox cb07;
    private CheckBox cb06;
    private CheckBox cb05;
    private CheckBox cb04;
    private CheckBox cb03;
    private CheckBox cb02;
    private CheckBox cb01;
    private Label label4;
    private TextBox txtGialapngaychuara;
    private Label label2;
    private Label label1;
    private TextBox txtBiendongay;
    private Label label13;
    private Button btnThongke;
    private DateTimePicker dtNgayXem;
    private Label label3;
    private WebBrowser wbHienthi;
    private Button button5;
    private Button button4;
    private Button button3;
    private Button button2;
    private Button button1;
    private Button button6;
    private Button button7;
    private Button button8;
    private Button button9;
    private Button button10;

    public TabTanxuatcaploto()
    {
      this.InitializeComponent();
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.panel2 = new Panel();
      this.label6 = new Label();
      this.label5 = new Label();
      this.btnTronhet = new Button();
      this.cb80 = new CheckBox();
      this.cb60 = new CheckBox();
      this.cb40 = new CheckBox();
      this.cb20 = new CheckBox();
      this.cb00 = new CheckBox();
      this.cb89 = new CheckBox();
      this.cb88 = new CheckBox();
      this.cb87 = new CheckBox();
      this.cb86 = new CheckBox();
      this.cb85 = new CheckBox();
      this.cb84 = new CheckBox();
      this.cb83 = new CheckBox();
      this.cb82 = new CheckBox();
      this.cb81 = new CheckBox();
      this.cb69 = new CheckBox();
      this.cb68 = new CheckBox();
      this.cb67 = new CheckBox();
      this.cb66 = new CheckBox();
      this.cb65 = new CheckBox();
      this.cb64 = new CheckBox();
      this.cb63 = new CheckBox();
      this.cb62 = new CheckBox();
      this.cb61 = new CheckBox();
      this.cb49 = new CheckBox();
      this.cb48 = new CheckBox();
      this.cb47 = new CheckBox();
      this.cb46 = new CheckBox();
      this.cb45 = new CheckBox();
      this.cb44 = new CheckBox();
      this.cb43 = new CheckBox();
      this.cb42 = new CheckBox();
      this.cb41 = new CheckBox();
      this.cb29 = new CheckBox();
      this.cb28 = new CheckBox();
      this.cb27 = new CheckBox();
      this.cb26 = new CheckBox();
      this.cb25 = new CheckBox();
      this.cb24 = new CheckBox();
      this.cb23 = new CheckBox();
      this.cb22 = new CheckBox();
      this.cb21 = new CheckBox();
      this.cb09 = new CheckBox();
      this.cb08 = new CheckBox();
      this.cb07 = new CheckBox();
      this.cb06 = new CheckBox();
      this.cb05 = new CheckBox();
      this.cb04 = new CheckBox();
      this.cb03 = new CheckBox();
      this.cb02 = new CheckBox();
      this.cb01 = new CheckBox();
      this.label4 = new Label();
      this.txtGialapngaychuara = new TextBox();
      this.label2 = new Label();
      this.label1 = new Label();
      this.txtBiendongay = new TextBox();
      this.label13 = new Label();
      this.btnThongke = new Button();
      this.dtNgayXem = new DateTimePicker();
      this.label3 = new Label();
      this.wbHienthi = new WebBrowser();
      this.button1 = new Button();
      this.button2 = new Button();
      this.button3 = new Button();
      this.button4 = new Button();
      this.button5 = new Button();
      this.button6 = new Button();
      this.button7 = new Button();
      this.button8 = new Button();
      this.button9 = new Button();
      this.button10 = new Button();
      this.panel2.SuspendLayout();
      this.SuspendLayout();
      this.panel2.BackColor = Color.Transparent;
      this.panel2.Controls.Add((Control) this.button6);
      this.panel2.Controls.Add((Control) this.button7);
      this.panel2.Controls.Add((Control) this.button8);
      this.panel2.Controls.Add((Control) this.button9);
      this.panel2.Controls.Add((Control) this.button10);
      this.panel2.Controls.Add((Control) this.button5);
      this.panel2.Controls.Add((Control) this.button4);
      this.panel2.Controls.Add((Control) this.button3);
      this.panel2.Controls.Add((Control) this.button2);
      this.panel2.Controls.Add((Control) this.button1);
      this.panel2.Controls.Add((Control) this.label6);
      this.panel2.Controls.Add((Control) this.label5);
      this.panel2.Controls.Add((Control) this.btnTronhet);
      this.panel2.Controls.Add((Control) this.cb80);
      this.panel2.Controls.Add((Control) this.cb60);
      this.panel2.Controls.Add((Control) this.cb40);
      this.panel2.Controls.Add((Control) this.cb20);
      this.panel2.Controls.Add((Control) this.cb00);
      this.panel2.Controls.Add((Control) this.cb89);
      this.panel2.Controls.Add((Control) this.cb88);
      this.panel2.Controls.Add((Control) this.cb87);
      this.panel2.Controls.Add((Control) this.cb86);
      this.panel2.Controls.Add((Control) this.cb85);
      this.panel2.Controls.Add((Control) this.cb84);
      this.panel2.Controls.Add((Control) this.cb83);
      this.panel2.Controls.Add((Control) this.cb82);
      this.panel2.Controls.Add((Control) this.cb81);
      this.panel2.Controls.Add((Control) this.cb69);
      this.panel2.Controls.Add((Control) this.cb68);
      this.panel2.Controls.Add((Control) this.cb67);
      this.panel2.Controls.Add((Control) this.cb66);
      this.panel2.Controls.Add((Control) this.cb65);
      this.panel2.Controls.Add((Control) this.cb64);
      this.panel2.Controls.Add((Control) this.cb63);
      this.panel2.Controls.Add((Control) this.cb62);
      this.panel2.Controls.Add((Control) this.cb61);
      this.panel2.Controls.Add((Control) this.cb49);
      this.panel2.Controls.Add((Control) this.cb48);
      this.panel2.Controls.Add((Control) this.cb47);
      this.panel2.Controls.Add((Control) this.cb46);
      this.panel2.Controls.Add((Control) this.cb45);
      this.panel2.Controls.Add((Control) this.cb44);
      this.panel2.Controls.Add((Control) this.cb43);
      this.panel2.Controls.Add((Control) this.cb42);
      this.panel2.Controls.Add((Control) this.cb41);
      this.panel2.Controls.Add((Control) this.cb29);
      this.panel2.Controls.Add((Control) this.cb28);
      this.panel2.Controls.Add((Control) this.cb27);
      this.panel2.Controls.Add((Control) this.cb26);
      this.panel2.Controls.Add((Control) this.cb25);
      this.panel2.Controls.Add((Control) this.cb24);
      this.panel2.Controls.Add((Control) this.cb23);
      this.panel2.Controls.Add((Control) this.cb22);
      this.panel2.Controls.Add((Control) this.cb21);
      this.panel2.Controls.Add((Control) this.cb09);
      this.panel2.Controls.Add((Control) this.cb08);
      this.panel2.Controls.Add((Control) this.cb07);
      this.panel2.Controls.Add((Control) this.cb06);
      this.panel2.Controls.Add((Control) this.cb05);
      this.panel2.Controls.Add((Control) this.cb04);
      this.panel2.Controls.Add((Control) this.cb03);
      this.panel2.Controls.Add((Control) this.cb02);
      this.panel2.Controls.Add((Control) this.cb01);
      this.panel2.Controls.Add((Control) this.label4);
      this.panel2.Controls.Add((Control) this.txtGialapngaychuara);
      this.panel2.Controls.Add((Control) this.label2);
      this.panel2.Controls.Add((Control) this.label1);
      this.panel2.Controls.Add((Control) this.txtBiendongay);
      this.panel2.Controls.Add((Control) this.label13);
      this.panel2.Controls.Add((Control) this.btnThongke);
      this.panel2.Controls.Add((Control) this.dtNgayXem);
      this.panel2.Controls.Add((Control) this.label3);
      this.panel2.Dock = DockStyle.Top;
      this.panel2.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.panel2.Location = new Point(0, 0);
      this.panel2.Margin = new Padding(0);
      this.panel2.Name = "panel2";
      this.panel2.Size = new Size(1100, 181);
      this.panel2.TabIndex = 2;
      this.label6.BackColor = Color.WhiteSmoke;
      this.label6.Font = new Font("Arial", 11.25f, FontStyle.Italic, GraphicsUnit.Point, (byte) 163);
      this.label6.ForeColor = Color.Black;
      this.label6.Location = new Point(5, 158);
      this.label6.Name = "label6";
      this.label6.Size = new Size(72, 18);
      this.label6.TabIndex = 124;
      this.label6.Text = "☞ Gợi ý :";
      this.label6.TextAlign = ContentAlignment.MiddleLeft;
      this.label5.AutoSize = true;
      this.label5.Font = new Font("Arial", 11.25f, FontStyle.Italic, GraphicsUnit.Point, (byte) 163);
      this.label5.ForeColor = Color.DimGray;
      this.label5.Location = new Point(6, 161);
      this.label5.Name = "label5";
      this.label5.Size = new Size(893, 17);
      this.label5.TabIndex = 31;
      this.label5.Text = "                  Giả lập ngày chưa ra giúp cho việc nhìn nhận lô tô được tổng quan hơn, dự đoán khung được chuẩn xác hơn, tránh xa bờ !!!!!";
      this.btnTronhet.BackColor = Color.Teal;
      this.btnTronhet.Cursor = Cursors.Hand;
      this.btnTronhet.FlatStyle = FlatStyle.Flat;
      this.btnTronhet.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.btnTronhet.ForeColor = Color.White;
      this.btnTronhet.Location = new Point(718, 5);
      this.btnTronhet.Margin = new Padding(3, 0, 3, 0);
      this.btnTronhet.Name = "btnTronhet";
      this.btnTronhet.Size = new Size(77, 24);
      this.btnTronhet.TabIndex = 3;
      this.btnTronhet.Text = "Chọn hết";
      this.btnTronhet.TextAlign = ContentAlignment.TopCenter;
      this.btnTronhet.UseVisualStyleBackColor = false;
      this.cb80.AutoSize = true;
      this.cb80.BackColor = Color.White;
      this.cb80.Cursor = Cursors.Hand;
      this.cb80.FlatStyle = FlatStyle.Flat;
      this.cb80.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb80.ForeColor = Color.DimGray;
      this.cb80.Location = new Point(11, 135);
      this.cb80.Name = "cb80";
      this.cb80.Size = new Size(56, 20);
      this.cb80.TabIndex = 85;
      this.cb80.Text = "56-65";
      this.cb80.UseVisualStyleBackColor = false;
      this.cb60.AutoSize = true;
      this.cb60.BackColor = Color.White;
      this.cb60.Cursor = Cursors.Hand;
      this.cb60.FlatStyle = FlatStyle.Flat;
      this.cb60.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb60.ForeColor = Color.DimGray;
      this.cb60.Location = new Point(11, 111);
      this.cb60.Name = "cb60";
      this.cb60.Size = new Size(56, 20);
      this.cb60.TabIndex = 65;
      this.cb60.Text = "36-63";
      this.cb60.UseVisualStyleBackColor = false;
      this.cb40.AutoSize = true;
      this.cb40.BackColor = Color.White;
      this.cb40.Cursor = Cursors.Hand;
      this.cb40.FlatStyle = FlatStyle.Flat;
      this.cb40.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb40.ForeColor = Color.DimGray;
      this.cb40.Location = new Point(11, 87);
      this.cb40.Name = "cb40";
      this.cb40.Size = new Size(56, 20);
      this.cb40.TabIndex = 45;
      this.cb40.Text = "23-32";
      this.cb40.UseVisualStyleBackColor = false;
      this.cb20.AutoSize = true;
      this.cb20.BackColor = Color.White;
      this.cb20.Cursor = Cursors.Hand;
      this.cb20.FlatStyle = FlatStyle.Flat;
      this.cb20.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb20.ForeColor = Color.DimGray;
      this.cb20.Location = new Point(11, 63);
      this.cb20.Name = "cb20";
      this.cb20.Size = new Size(55, 20);
      this.cb20.TabIndex = 25;
      this.cb20.Text = "11-66";
      this.cb20.UseVisualStyleBackColor = false;
      this.cb00.AutoSize = true;
      this.cb00.BackColor = Color.White;
      this.cb00.Cursor = Cursors.Hand;
      this.cb00.FlatStyle = FlatStyle.Flat;
      this.cb00.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb00.ForeColor = Color.DimGray;
      this.cb00.Location = new Point(11, 39);
      this.cb00.Name = "cb00";
      this.cb00.Size = new Size(56, 20);
      this.cb00.TabIndex = 5;
      this.cb00.Text = "00-55";
      this.cb00.UseVisualStyleBackColor = false;
      this.cb89.AutoSize = true;
      this.cb89.BackColor = Color.White;
      this.cb89.Cursor = Cursors.Hand;
      this.cb89.FlatStyle = FlatStyle.Flat;
      this.cb89.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb89.ForeColor = Color.DimGray;
      this.cb89.Location = new Point(560, 135);
      this.cb89.Name = "cb89";
      this.cb89.Size = new Size(56, 20);
      this.cb89.TabIndex = 94;
      this.cb89.Text = "89-98";
      this.cb89.UseVisualStyleBackColor = false;
      this.cb88.AutoSize = true;
      this.cb88.BackColor = Color.White;
      this.cb88.Cursor = Cursors.Hand;
      this.cb88.FlatStyle = FlatStyle.Flat;
      this.cb88.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb88.ForeColor = Color.DimGray;
      this.cb88.Location = new Point(499, 135);
      this.cb88.Name = "cb88";
      this.cb88.Size = new Size(56, 20);
      this.cb88.TabIndex = 93;
      this.cb88.Text = "79-97";
      this.cb88.UseVisualStyleBackColor = false;
      this.cb87.AutoSize = true;
      this.cb87.BackColor = Color.White;
      this.cb87.Cursor = Cursors.Hand;
      this.cb87.FlatStyle = FlatStyle.Flat;
      this.cb87.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb87.ForeColor = Color.DimGray;
      this.cb87.Location = new Point(438, 135);
      this.cb87.Name = "cb87";
      this.cb87.Size = new Size(56, 20);
      this.cb87.TabIndex = 92;
      this.cb87.Text = "78-87";
      this.cb87.UseVisualStyleBackColor = false;
      this.cb86.AutoSize = true;
      this.cb86.BackColor = Color.White;
      this.cb86.Cursor = Cursors.Hand;
      this.cb86.FlatStyle = FlatStyle.Flat;
      this.cb86.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb86.ForeColor = Color.DimGray;
      this.cb86.Location = new Point(377, 135);
      this.cb86.Name = "cb86";
      this.cb86.Size = new Size(56, 20);
      this.cb86.TabIndex = 91;
      this.cb86.Text = "69-96";
      this.cb86.UseVisualStyleBackColor = false;
      this.cb85.AutoSize = true;
      this.cb85.BackColor = Color.White;
      this.cb85.Cursor = Cursors.Hand;
      this.cb85.FlatStyle = FlatStyle.Flat;
      this.cb85.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb85.ForeColor = Color.DimGray;
      this.cb85.Location = new Point(316, 135);
      this.cb85.Name = "cb85";
      this.cb85.Size = new Size(56, 20);
      this.cb85.TabIndex = 90;
      this.cb85.Text = "68-86";
      this.cb85.UseVisualStyleBackColor = false;
      this.cb84.AutoSize = true;
      this.cb84.BackColor = Color.White;
      this.cb84.Cursor = Cursors.Hand;
      this.cb84.FlatStyle = FlatStyle.Flat;
      this.cb84.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb84.ForeColor = Color.DimGray;
      this.cb84.Location = new Point((int) byte.MaxValue, 135);
      this.cb84.Name = "cb84";
      this.cb84.Size = new Size(56, 20);
      this.cb84.TabIndex = 89;
      this.cb84.Text = "67-76";
      this.cb84.UseVisualStyleBackColor = false;
      this.cb83.AutoSize = true;
      this.cb83.BackColor = Color.White;
      this.cb83.Cursor = Cursors.Hand;
      this.cb83.FlatStyle = FlatStyle.Flat;
      this.cb83.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb83.ForeColor = Color.DimGray;
      this.cb83.Location = new Point(194, 135);
      this.cb83.Name = "cb83";
      this.cb83.Size = new Size(56, 20);
      this.cb83.TabIndex = 88;
      this.cb83.Text = "59-95";
      this.cb83.UseVisualStyleBackColor = false;
      this.cb82.AutoSize = true;
      this.cb82.BackColor = Color.White;
      this.cb82.Cursor = Cursors.Hand;
      this.cb82.FlatStyle = FlatStyle.Flat;
      this.cb82.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb82.ForeColor = Color.DimGray;
      this.cb82.Location = new Point(133, 135);
      this.cb82.Name = "cb82";
      this.cb82.Size = new Size(56, 20);
      this.cb82.TabIndex = 87;
      this.cb82.Text = "58-85";
      this.cb82.UseVisualStyleBackColor = false;
      this.cb81.AutoSize = true;
      this.cb81.BackColor = Color.White;
      this.cb81.Cursor = Cursors.Hand;
      this.cb81.FlatStyle = FlatStyle.Flat;
      this.cb81.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb81.ForeColor = Color.DimGray;
      this.cb81.Location = new Point(72, 135);
      this.cb81.Name = "cb81";
      this.cb81.Size = new Size(56, 20);
      this.cb81.TabIndex = 86;
      this.cb81.Text = "57-75";
      this.cb81.UseVisualStyleBackColor = false;
      this.cb69.AutoSize = true;
      this.cb69.BackColor = Color.White;
      this.cb69.Cursor = Cursors.Hand;
      this.cb69.FlatStyle = FlatStyle.Flat;
      this.cb69.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb69.ForeColor = Color.DimGray;
      this.cb69.Location = new Point(560, 111);
      this.cb69.Name = "cb69";
      this.cb69.Size = new Size(56, 20);
      this.cb69.TabIndex = 74;
      this.cb69.Text = "49-94";
      this.cb69.UseVisualStyleBackColor = false;
      this.cb68.AutoSize = true;
      this.cb68.BackColor = Color.White;
      this.cb68.Cursor = Cursors.Hand;
      this.cb68.FlatStyle = FlatStyle.Flat;
      this.cb68.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb68.ForeColor = Color.DimGray;
      this.cb68.Location = new Point(499, 111);
      this.cb68.Name = "cb68";
      this.cb68.Size = new Size(56, 20);
      this.cb68.TabIndex = 73;
      this.cb68.Text = "48-84";
      this.cb68.UseVisualStyleBackColor = false;
      this.cb67.AutoSize = true;
      this.cb67.BackColor = Color.White;
      this.cb67.Cursor = Cursors.Hand;
      this.cb67.FlatStyle = FlatStyle.Flat;
      this.cb67.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb67.ForeColor = Color.DimGray;
      this.cb67.Location = new Point(438, 111);
      this.cb67.Name = "cb67";
      this.cb67.Size = new Size(56, 20);
      this.cb67.TabIndex = 72;
      this.cb67.Text = "47-74";
      this.cb67.UseVisualStyleBackColor = false;
      this.cb66.AutoSize = true;
      this.cb66.BackColor = Color.White;
      this.cb66.Cursor = Cursors.Hand;
      this.cb66.FlatStyle = FlatStyle.Flat;
      this.cb66.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb66.ForeColor = Color.DimGray;
      this.cb66.Location = new Point(377, 111);
      this.cb66.Name = "cb66";
      this.cb66.Size = new Size(56, 20);
      this.cb66.TabIndex = 71;
      this.cb66.Text = "46-64";
      this.cb66.UseVisualStyleBackColor = false;
      this.cb65.AutoSize = true;
      this.cb65.BackColor = Color.White;
      this.cb65.Cursor = Cursors.Hand;
      this.cb65.FlatStyle = FlatStyle.Flat;
      this.cb65.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb65.ForeColor = Color.DimGray;
      this.cb65.Location = new Point(316, 111);
      this.cb65.Name = "cb65";
      this.cb65.Size = new Size(56, 20);
      this.cb65.TabIndex = 70;
      this.cb65.Text = "45-54";
      this.cb65.UseVisualStyleBackColor = false;
      this.cb64.AutoSize = true;
      this.cb64.BackColor = Color.White;
      this.cb64.Cursor = Cursors.Hand;
      this.cb64.FlatStyle = FlatStyle.Flat;
      this.cb64.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb64.ForeColor = Color.DimGray;
      this.cb64.Location = new Point((int) byte.MaxValue, 111);
      this.cb64.Name = "cb64";
      this.cb64.Size = new Size(56, 20);
      this.cb64.TabIndex = 69;
      this.cb64.Text = "44-99";
      this.cb64.UseVisualStyleBackColor = false;
      this.cb63.AutoSize = true;
      this.cb63.BackColor = Color.White;
      this.cb63.Cursor = Cursors.Hand;
      this.cb63.FlatStyle = FlatStyle.Flat;
      this.cb63.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb63.ForeColor = Color.DimGray;
      this.cb63.Location = new Point(194, 111);
      this.cb63.Name = "cb63";
      this.cb63.Size = new Size(56, 20);
      this.cb63.TabIndex = 68;
      this.cb63.Text = "39-93";
      this.cb63.UseVisualStyleBackColor = false;
      this.cb62.AutoSize = true;
      this.cb62.BackColor = Color.White;
      this.cb62.Cursor = Cursors.Hand;
      this.cb62.FlatStyle = FlatStyle.Flat;
      this.cb62.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb62.ForeColor = Color.DimGray;
      this.cb62.Location = new Point(133, 111);
      this.cb62.Name = "cb62";
      this.cb62.Size = new Size(56, 20);
      this.cb62.TabIndex = 67;
      this.cb62.Text = "38-83";
      this.cb62.UseVisualStyleBackColor = false;
      this.cb61.AutoSize = true;
      this.cb61.BackColor = Color.White;
      this.cb61.Cursor = Cursors.Hand;
      this.cb61.FlatStyle = FlatStyle.Flat;
      this.cb61.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb61.ForeColor = Color.DimGray;
      this.cb61.Location = new Point(72, 111);
      this.cb61.Name = "cb61";
      this.cb61.Size = new Size(56, 20);
      this.cb61.TabIndex = 66;
      this.cb61.Text = "37-73";
      this.cb61.UseVisualStyleBackColor = false;
      this.cb49.AutoSize = true;
      this.cb49.BackColor = Color.White;
      this.cb49.Cursor = Cursors.Hand;
      this.cb49.FlatStyle = FlatStyle.Flat;
      this.cb49.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb49.ForeColor = Color.DimGray;
      this.cb49.Location = new Point(560, 87);
      this.cb49.Name = "cb49";
      this.cb49.Size = new Size(56, 20);
      this.cb49.TabIndex = 54;
      this.cb49.Text = "35-53";
      this.cb49.UseVisualStyleBackColor = false;
      this.cb48.AutoSize = true;
      this.cb48.BackColor = Color.White;
      this.cb48.Cursor = Cursors.Hand;
      this.cb48.FlatStyle = FlatStyle.Flat;
      this.cb48.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb48.ForeColor = Color.DimGray;
      this.cb48.Location = new Point(499, 87);
      this.cb48.Name = "cb48";
      this.cb48.Size = new Size(56, 20);
      this.cb48.TabIndex = 53;
      this.cb48.Text = "34-43";
      this.cb48.UseVisualStyleBackColor = false;
      this.cb47.AutoSize = true;
      this.cb47.BackColor = Color.White;
      this.cb47.Cursor = Cursors.Hand;
      this.cb47.FlatStyle = FlatStyle.Flat;
      this.cb47.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb47.ForeColor = Color.DimGray;
      this.cb47.Location = new Point(438, 87);
      this.cb47.Name = "cb47";
      this.cb47.Size = new Size(56, 20);
      this.cb47.TabIndex = 52;
      this.cb47.Text = "33-88";
      this.cb47.UseVisualStyleBackColor = false;
      this.cb46.AutoSize = true;
      this.cb46.BackColor = Color.White;
      this.cb46.Cursor = Cursors.Hand;
      this.cb46.FlatStyle = FlatStyle.Flat;
      this.cb46.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb46.ForeColor = Color.DimGray;
      this.cb46.Location = new Point(377, 87);
      this.cb46.Name = "cb46";
      this.cb46.Size = new Size(56, 20);
      this.cb46.TabIndex = 51;
      this.cb46.Text = "29-92";
      this.cb46.UseVisualStyleBackColor = false;
      this.cb45.AutoSize = true;
      this.cb45.BackColor = Color.White;
      this.cb45.Cursor = Cursors.Hand;
      this.cb45.FlatStyle = FlatStyle.Flat;
      this.cb45.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb45.ForeColor = Color.DimGray;
      this.cb45.Location = new Point(316, 87);
      this.cb45.Name = "cb45";
      this.cb45.Size = new Size(56, 20);
      this.cb45.TabIndex = 50;
      this.cb45.Text = "28-82";
      this.cb45.UseVisualStyleBackColor = false;
      this.cb44.AutoSize = true;
      this.cb44.BackColor = Color.White;
      this.cb44.Cursor = Cursors.Hand;
      this.cb44.FlatStyle = FlatStyle.Flat;
      this.cb44.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb44.ForeColor = Color.DimGray;
      this.cb44.Location = new Point((int) byte.MaxValue, 87);
      this.cb44.Name = "cb44";
      this.cb44.Size = new Size(56, 20);
      this.cb44.TabIndex = 49;
      this.cb44.Text = "27-72";
      this.cb44.UseVisualStyleBackColor = false;
      this.cb43.AutoSize = true;
      this.cb43.BackColor = Color.White;
      this.cb43.Cursor = Cursors.Hand;
      this.cb43.FlatStyle = FlatStyle.Flat;
      this.cb43.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb43.ForeColor = Color.DimGray;
      this.cb43.Location = new Point(194, 87);
      this.cb43.Name = "cb43";
      this.cb43.Size = new Size(56, 20);
      this.cb43.TabIndex = 48;
      this.cb43.Text = "26-62";
      this.cb43.UseVisualStyleBackColor = false;
      this.cb42.AutoSize = true;
      this.cb42.BackColor = Color.White;
      this.cb42.Cursor = Cursors.Hand;
      this.cb42.FlatStyle = FlatStyle.Flat;
      this.cb42.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb42.ForeColor = Color.DimGray;
      this.cb42.Location = new Point(133, 87);
      this.cb42.Name = "cb42";
      this.cb42.Size = new Size(56, 20);
      this.cb42.TabIndex = 47;
      this.cb42.Text = "25-52";
      this.cb42.UseVisualStyleBackColor = false;
      this.cb41.AutoSize = true;
      this.cb41.BackColor = Color.White;
      this.cb41.Cursor = Cursors.Hand;
      this.cb41.FlatStyle = FlatStyle.Flat;
      this.cb41.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb41.ForeColor = Color.DimGray;
      this.cb41.Location = new Point(72, 87);
      this.cb41.Name = "cb41";
      this.cb41.Size = new Size(56, 20);
      this.cb41.TabIndex = 46;
      this.cb41.Text = "24-42";
      this.cb41.UseVisualStyleBackColor = false;
      this.cb29.AutoSize = true;
      this.cb29.BackColor = Color.White;
      this.cb29.Cursor = Cursors.Hand;
      this.cb29.FlatStyle = FlatStyle.Flat;
      this.cb29.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb29.ForeColor = Color.DimGray;
      this.cb29.Location = new Point(560, 63);
      this.cb29.Name = "cb29";
      this.cb29.Size = new Size(56, 20);
      this.cb29.TabIndex = 34;
      this.cb29.Text = "22-77";
      this.cb29.UseVisualStyleBackColor = false;
      this.cb28.AutoSize = true;
      this.cb28.BackColor = Color.White;
      this.cb28.Cursor = Cursors.Hand;
      this.cb28.FlatStyle = FlatStyle.Flat;
      this.cb28.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb28.ForeColor = Color.DimGray;
      this.cb28.Location = new Point(499, 63);
      this.cb28.Name = "cb28";
      this.cb28.Size = new Size(56, 20);
      this.cb28.TabIndex = 33;
      this.cb28.Text = "19-91";
      this.cb28.UseVisualStyleBackColor = false;
      this.cb27.AutoSize = true;
      this.cb27.BackColor = Color.White;
      this.cb27.Cursor = Cursors.Hand;
      this.cb27.FlatStyle = FlatStyle.Flat;
      this.cb27.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb27.ForeColor = Color.DimGray;
      this.cb27.Location = new Point(438, 63);
      this.cb27.Name = "cb27";
      this.cb27.Size = new Size(56, 20);
      this.cb27.TabIndex = 32;
      this.cb27.Text = "18-81";
      this.cb27.UseVisualStyleBackColor = false;
      this.cb26.AutoSize = true;
      this.cb26.BackColor = Color.White;
      this.cb26.Cursor = Cursors.Hand;
      this.cb26.FlatStyle = FlatStyle.Flat;
      this.cb26.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb26.ForeColor = Color.DimGray;
      this.cb26.Location = new Point(377, 63);
      this.cb26.Name = "cb26";
      this.cb26.Size = new Size(56, 20);
      this.cb26.TabIndex = 31;
      this.cb26.Text = "17-71";
      this.cb26.UseVisualStyleBackColor = false;
      this.cb25.AutoSize = true;
      this.cb25.BackColor = Color.White;
      this.cb25.Cursor = Cursors.Hand;
      this.cb25.FlatStyle = FlatStyle.Flat;
      this.cb25.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb25.ForeColor = Color.DimGray;
      this.cb25.Location = new Point(316, 63);
      this.cb25.Name = "cb25";
      this.cb25.Size = new Size(56, 20);
      this.cb25.TabIndex = 30;
      this.cb25.Text = "16-61";
      this.cb25.UseVisualStyleBackColor = false;
      this.cb24.AutoSize = true;
      this.cb24.BackColor = Color.White;
      this.cb24.Cursor = Cursors.Hand;
      this.cb24.FlatStyle = FlatStyle.Flat;
      this.cb24.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb24.ForeColor = Color.DimGray;
      this.cb24.Location = new Point((int) byte.MaxValue, 63);
      this.cb24.Name = "cb24";
      this.cb24.Size = new Size(56, 20);
      this.cb24.TabIndex = 29;
      this.cb24.Text = "15-51";
      this.cb24.UseVisualStyleBackColor = false;
      this.cb23.AutoSize = true;
      this.cb23.BackColor = Color.White;
      this.cb23.Cursor = Cursors.Hand;
      this.cb23.FlatStyle = FlatStyle.Flat;
      this.cb23.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb23.ForeColor = Color.DimGray;
      this.cb23.Location = new Point(194, 63);
      this.cb23.Name = "cb23";
      this.cb23.Size = new Size(56, 20);
      this.cb23.TabIndex = 28;
      this.cb23.Text = "14-41";
      this.cb23.UseVisualStyleBackColor = false;
      this.cb22.AutoSize = true;
      this.cb22.BackColor = Color.White;
      this.cb22.Cursor = Cursors.Hand;
      this.cb22.FlatStyle = FlatStyle.Flat;
      this.cb22.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb22.ForeColor = Color.DimGray;
      this.cb22.Location = new Point(133, 63);
      this.cb22.Name = "cb22";
      this.cb22.Size = new Size(56, 20);
      this.cb22.TabIndex = 27;
      this.cb22.Text = "13-31";
      this.cb22.UseVisualStyleBackColor = false;
      this.cb21.AutoSize = true;
      this.cb21.BackColor = Color.White;
      this.cb21.Cursor = Cursors.Hand;
      this.cb21.FlatStyle = FlatStyle.Flat;
      this.cb21.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb21.ForeColor = Color.DimGray;
      this.cb21.Location = new Point(72, 63);
      this.cb21.Name = "cb21";
      this.cb21.Size = new Size(56, 20);
      this.cb21.TabIndex = 26;
      this.cb21.Text = "12-21";
      this.cb21.UseVisualStyleBackColor = false;
      this.cb09.AutoSize = true;
      this.cb09.BackColor = Color.White;
      this.cb09.Cursor = Cursors.Hand;
      this.cb09.FlatStyle = FlatStyle.Flat;
      this.cb09.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb09.ForeColor = Color.DimGray;
      this.cb09.Location = new Point(560, 41);
      this.cb09.Name = "cb09";
      this.cb09.Size = new Size(56, 20);
      this.cb09.TabIndex = 14;
      this.cb09.Text = "09-90";
      this.cb09.UseVisualStyleBackColor = false;
      this.cb08.AutoSize = true;
      this.cb08.BackColor = Color.White;
      this.cb08.Cursor = Cursors.Hand;
      this.cb08.FlatStyle = FlatStyle.Flat;
      this.cb08.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb08.ForeColor = Color.DimGray;
      this.cb08.Location = new Point(499, 41);
      this.cb08.Name = "cb08";
      this.cb08.Size = new Size(56, 20);
      this.cb08.TabIndex = 13;
      this.cb08.Text = "08-80";
      this.cb08.UseVisualStyleBackColor = false;
      this.cb07.AutoSize = true;
      this.cb07.BackColor = Color.White;
      this.cb07.Cursor = Cursors.Hand;
      this.cb07.FlatStyle = FlatStyle.Flat;
      this.cb07.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb07.ForeColor = Color.DimGray;
      this.cb07.Location = new Point(438, 41);
      this.cb07.Name = "cb07";
      this.cb07.Size = new Size(56, 20);
      this.cb07.TabIndex = 12;
      this.cb07.Text = "07-70";
      this.cb07.UseVisualStyleBackColor = false;
      this.cb06.AutoSize = true;
      this.cb06.BackColor = Color.White;
      this.cb06.Cursor = Cursors.Hand;
      this.cb06.FlatStyle = FlatStyle.Flat;
      this.cb06.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb06.ForeColor = Color.DimGray;
      this.cb06.Location = new Point(377, 39);
      this.cb06.Name = "cb06";
      this.cb06.Size = new Size(56, 20);
      this.cb06.TabIndex = 11;
      this.cb06.Text = "06-60";
      this.cb06.UseVisualStyleBackColor = false;
      this.cb05.AutoSize = true;
      this.cb05.BackColor = Color.White;
      this.cb05.Cursor = Cursors.Hand;
      this.cb05.FlatStyle = FlatStyle.Flat;
      this.cb05.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb05.ForeColor = Color.DimGray;
      this.cb05.Location = new Point(316, 39);
      this.cb05.Name = "cb05";
      this.cb05.Size = new Size(56, 20);
      this.cb05.TabIndex = 10;
      this.cb05.Text = "05-50";
      this.cb05.UseVisualStyleBackColor = false;
      this.cb04.AutoSize = true;
      this.cb04.BackColor = Color.White;
      this.cb04.Cursor = Cursors.Hand;
      this.cb04.FlatStyle = FlatStyle.Flat;
      this.cb04.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb04.ForeColor = Color.DimGray;
      this.cb04.Location = new Point((int) byte.MaxValue, 39);
      this.cb04.Name = "cb04";
      this.cb04.Size = new Size(56, 20);
      this.cb04.TabIndex = 9;
      this.cb04.Text = "04-40";
      this.cb04.UseVisualStyleBackColor = false;
      this.cb03.AutoSize = true;
      this.cb03.BackColor = Color.White;
      this.cb03.Cursor = Cursors.Hand;
      this.cb03.FlatStyle = FlatStyle.Flat;
      this.cb03.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb03.ForeColor = Color.DimGray;
      this.cb03.Location = new Point(194, 39);
      this.cb03.Name = "cb03";
      this.cb03.Size = new Size(56, 20);
      this.cb03.TabIndex = 8;
      this.cb03.Text = "03-30";
      this.cb03.UseVisualStyleBackColor = false;
      this.cb02.AutoSize = true;
      this.cb02.BackColor = Color.White;
      this.cb02.Cursor = Cursors.Hand;
      this.cb02.FlatStyle = FlatStyle.Flat;
      this.cb02.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb02.ForeColor = Color.DimGray;
      this.cb02.Location = new Point(133, 39);
      this.cb02.Name = "cb02";
      this.cb02.Size = new Size(56, 20);
      this.cb02.TabIndex = 7;
      this.cb02.Text = "02-20";
      this.cb02.UseVisualStyleBackColor = false;
      this.cb01.AutoSize = true;
      this.cb01.BackColor = Color.White;
      this.cb01.Cursor = Cursors.Hand;
      this.cb01.FlatStyle = FlatStyle.Flat;
      this.cb01.Font = new Font("Arial", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.cb01.ForeColor = Color.DimGray;
      this.cb01.Location = new Point(72, 39);
      this.cb01.Name = "cb01";
      this.cb01.Size = new Size(56, 20);
      this.cb01.TabIndex = 6;
      this.cb01.Text = "01-10";
      this.cb01.UseVisualStyleBackColor = false;
      this.label4.AutoSize = true;
      this.label4.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label4.ForeColor = Color.Black;
      this.label4.Location = new Point(632, 10);
      this.label4.Name = "label4";
      this.label4.Size = new Size(36, 16);
      this.label4.TabIndex = 30;
      this.label4.Text = "ngày";
      this.txtGialapngaychuara.BorderStyle = BorderStyle.FixedSingle;
      this.txtGialapngaychuara.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.txtGialapngaychuara.ForeColor = Color.Red;
      this.txtGialapngaychuara.Location = new Point(574, 8);
      this.txtGialapngaychuara.Name = "txtGialapngaychuara";
      this.txtGialapngaychuara.Size = new Size(58, 21);
      this.txtGialapngaychuara.TabIndex = 2;
      this.txtGialapngaychuara.Text = "0";
      this.label2.AutoSize = true;
      this.label2.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label2.ForeColor = Color.Black;
      this.label2.Location = new Point(448, 10);
      this.label2.Name = "label2";
      this.label2.Size = new Size((int) sbyte.MaxValue, 16);
      this.label2.TabIndex = 28;
      this.label2.Text = "giả lập ngày chưa ra";
      this.label1.AutoSize = true;
      this.label1.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label1.ForeColor = Color.Black;
      this.label1.Location = new Point(312, 10);
      this.label1.Name = "label1";
      this.label1.Size = new Size(89, 16);
      this.label1.TabIndex = 27;
      this.label1.Text = "ngày về trước";
      this.txtBiendongay.BorderStyle = BorderStyle.FixedSingle;
      this.txtBiendongay.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 163);
      this.txtBiendongay.ForeColor = Color.Red;
      this.txtBiendongay.Location = new Point(261, 8);
      this.txtBiendongay.Name = "txtBiendongay";
      this.txtBiendongay.Size = new Size(51, 21);
      this.txtBiendongay.TabIndex = 1;
      this.txtBiendongay.Text = "36";
      this.label13.AutoSize = true;
      this.label13.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label13.ForeColor = Color.Black;
      this.label13.Location = new Point(7, 10);
      this.label13.Name = "label13";
      this.label13.Size = new Size(65, 16);
      this.label13.TabIndex = 24;
      this.label13.Text = "Xem ngày";
      this.btnThongke.BackColor = Color.Teal;
      this.btnThongke.Cursor = Cursors.Hand;
      this.btnThongke.FlatStyle = FlatStyle.Flat;
      this.btnThongke.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.btnThongke.ForeColor = Color.White;
      this.btnThongke.Location = new Point(795, 5);
      this.btnThongke.Margin = new Padding(3, 0, 3, 0);
      this.btnThongke.Name = "btnThongke";
      this.btnThongke.Size = new Size(105, 24);
      this.btnThongke.TabIndex = 4;
      this.btnThongke.Text = "Thống kê";
      this.btnThongke.TextAlign = ContentAlignment.TopCenter;
      this.btnThongke.UseVisualStyleBackColor = true;
      this.dtNgayXem.CalendarFont = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.dtNgayXem.CalendarForeColor = Color.Red;
      this.dtNgayXem.CalendarMonthBackground = SystemColors.Info;
      this.dtNgayXem.CustomFormat = "dd/MM/yyyy";
      this.dtNgayXem.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.dtNgayXem.Format = DateTimePickerFormat.Custom;
      this.dtNgayXem.Location = new Point(72, 8);
      this.dtNgayXem.MinDate = new DateTime(2005, 1, 5, 0, 0, 0, 0);
      this.dtNgayXem.Name = "dtNgayXem";
      this.dtNgayXem.Size = new Size(103, 21);
      this.dtNgayXem.TabIndex = 0;
      this.label3.AutoSize = true;
      this.label3.Font = new Font("Arial", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label3.ForeColor = Color.Black;
      this.label3.Location = new Point(211, 10);
      this.label3.Name = "label3";
      this.label3.Size = new Size(50, 16);
      this.label3.TabIndex = 7;
      this.label3.Text = "biên độ";
      this.wbHienthi.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
      this.wbHienthi.Location = new Point(1, 183);
      this.wbHienthi.MinimumSize = new Size(20, 20);
      this.wbHienthi.Name = "wbHienthi";
      this.wbHienthi.Size = new Size(1115, 408);
      this.wbHienthi.TabIndex = 62;
      this.button1.BackColor = Color.PeachPuff;
      this.button1.FlatStyle = FlatStyle.Popup;
      this.button1.Location = new Point(635, 39);
      this.button1.Name = "button1";
      this.button1.Size = new Size(61, 22);
      this.button1.TabIndex = 125;
      this.button1.Text = "Chạm 0";
      this.button1.UseVisualStyleBackColor = false;
      this.button2.BackColor = Color.PeachPuff;
      this.button2.FlatStyle = FlatStyle.Popup;
      this.button2.Location = new Point(635, 63);
      this.button2.Name = "button2";
      this.button2.Size = new Size(61, 22);
      this.button2.TabIndex = 126;
      this.button2.Text = "Chạm 1";
      this.button2.UseVisualStyleBackColor = false;
      this.button3.BackColor = Color.PeachPuff;
      this.button3.FlatStyle = FlatStyle.Popup;
      this.button3.Location = new Point(635, 87);
      this.button3.Name = "button3";
      this.button3.Size = new Size(61, 22);
      this.button3.TabIndex = (int) sbyte.MaxValue;
      this.button3.Text = "Chạm 2";
      this.button3.UseVisualStyleBackColor = false;
      this.button4.BackColor = Color.PeachPuff;
      this.button4.FlatStyle = FlatStyle.Popup;
      this.button4.Location = new Point(635, 111);
      this.button4.Name = "button4";
      this.button4.Size = new Size(61, 22);
      this.button4.TabIndex = 128;
      this.button4.Text = "Chạm 3";
      this.button4.UseVisualStyleBackColor = false;
      this.button5.BackColor = Color.PeachPuff;
      this.button5.FlatStyle = FlatStyle.Popup;
      this.button5.Location = new Point(635, 135);
      this.button5.Name = "button5";
      this.button5.Size = new Size(61, 22);
      this.button5.TabIndex = 129;
      this.button5.Text = "Chạm 4";
      this.button5.UseVisualStyleBackColor = false;
      this.button6.BackColor = Color.PeachPuff;
      this.button6.FlatStyle = FlatStyle.Popup;
      this.button6.Location = new Point(702, 135);
      this.button6.Name = "button6";
      this.button6.Size = new Size(61, 22);
      this.button6.TabIndex = 134;
      this.button6.Text = "Chạm 9";
      this.button6.UseVisualStyleBackColor = false;
      this.button7.BackColor = Color.PeachPuff;
      this.button7.FlatStyle = FlatStyle.Popup;
      this.button7.Location = new Point(702, 111);
      this.button7.Name = "button7";
      this.button7.Size = new Size(61, 22);
      this.button7.TabIndex = 133;
      this.button7.Text = "Chạm 8";
      this.button7.UseVisualStyleBackColor = false;
      this.button8.BackColor = Color.PeachPuff;
      this.button8.FlatStyle = FlatStyle.Popup;
      this.button8.Location = new Point(702, 87);
      this.button8.Name = "button8";
      this.button8.Size = new Size(61, 22);
      this.button8.TabIndex = 132;
      this.button8.Text = "Chạm 7";
      this.button8.UseVisualStyleBackColor = false;
      this.button9.BackColor = Color.PeachPuff;
      this.button9.FlatStyle = FlatStyle.Popup;
      this.button9.Location = new Point(702, 63);
      this.button9.Name = "button9";
      this.button9.Size = new Size(61, 22);
      this.button9.TabIndex = 131;
      this.button9.Text = "Chạm 6";
      this.button9.UseVisualStyleBackColor = false;
      this.button10.BackColor = Color.PeachPuff;
      this.button10.FlatStyle = FlatStyle.Popup;
      this.button10.Location = new Point(702, 39);
      this.button10.Name = "button10";
      this.button10.Size = new Size(61, 22);
      this.button10.TabIndex = 130;
      this.button10.Text = "Chạm 5";
      this.button10.UseVisualStyleBackColor = false;
      this.AutoScaleDimensions = new SizeF(7f, 15f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.BackColor = Color.White;
      this.Controls.Add((Control) this.wbHienthi);
      this.Controls.Add((Control) this.panel2);
      this.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.Name = nameof (TabTanxuatcaploto);
      this.Size = new Size(1100, 591);
      this.panel2.ResumeLayout(false);
      this.panel2.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
